name: 'Lint Markdown & Frontmatter'
description: 'GitHub Action linting markdown &amp; its frontmatter content.'

outputs:
  changed: # id of output
    description: 'The changed files'

inputs:
  changed-files:
    description: 'Files to lint'
    required: true
  directories:
    description: 'Multiple directories to search in'
    required: true
  markdown-extensions:
    description: 'Multiple extensions of Markdown files to check for'
    required: true
  image-extensions:
    description: 'Multiple extensions of image files to check for'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
