name: "Lint Markdown & Frontmatter"
description: "GitHub Action linting markdown &amp; its frontmatter content."

inputs:
  github-token:
    description: "The GitHub token used to create an authenticated client"
    default: ${{ github.token }}
    required: false
  debug:
    description: "Whether to tell the GitHub client to log details of its requests"
    default: false
    required: false
  changed-files:
    description: "Files to lint"
    required: true
  directories:
    description: "Multiple directories to search in"
    required: true
  markdown-extensions:
    description: "Multiple extensions of Markdown files to check for"
    required: true
  image-extensions:
    description: "Multiple extensions of image files to check for"
    required: true
  fuzzy-search:
    description: "Should the existing projects be checked for duplicates with nearest neighbor (fuzzy) search"
    required: false

outputs:
  changed: # id of output
    description: "The changed files"

runs:
  using: "node12"
  main: "dist/index.js"
